version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Usa la versión de Node.js que necesites
    commands:
      - echo "Instalando dependencias..."
      - npm install typescript --save-dev  # Instala TypeScript como dependencia de desarrollo
      - npm ci  # Instala las dependencias del proyecto
  pre_build:
    commands:
      - echo "Preparando la construcción..."
      - npx tsc -v  # Verifica que tsc esté disponible
  build:
    commands:
      - echo "Compilando TypeScript..."
      - npm run build  # Ejecuta el script de construcción definido en package.json
  post_build:
    commands:
      - echo "Construcción completada"
artifacts:
  files:
    - "**/*"  # Incluye todos los archivos generados
  discard-paths: yes  # Descarta las rutas y solo incluye los archivos
