version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependencias..."
      - npm ci # Primero instala todo desde package-lock.json
      - npm install typescript --save-dev # Luego agrega TypeScript
  build:
    commands:
      - echo "Compilando TypeScript..."
      - npm run build
  post_build:
    commands:
      - echo "Construcción completada"
artifacts:
  files:
    - "**/*"
  discard-paths: yes
